### ISSUE TITLE
UnboundLocalError: local variable 'gray' referenced before assignment

### ISSUE THREAD

**Issue by theacceloguy** [windowsub0406/Vehicle-Detection-YOLO-ver#1]
Hello, 
I am having the following error when i am trying to compile the code. 
File "main.py", line 17, in <module>
    mtx, dist = calib()
  File "/usr/test_code/calibration.py", line 39, in calib
    ret, mtx, dist, rvecs, tvecs = cv2.calibrateCamera(objpoints, imgpoints, gray.shape[::-1], None, None)
UnboundLocalError: local variable 'gray' referenced before assignment

Please help.

**Comment by molyswu** [comment]
Have the same problem

**Comment by WWG1121** [comment]
Have the same problem

**Comment by alfamousts** [comment]
Hello, anyone know where is the location of file weights/yolo.ckpt 
I got this error in command line
`InvalidArgumentError (see above for traceback): Unsuccessful TensorSliceReader constructor: Failed to get matching files on weights/yolo.ckpt: Not found: FindFirstFile failed for: weights : The system cannot find the path specified.
; No such process`

**Comment by jiangkun1994** [comment]
For the

> weights/yolo.ckpt

I think you can download them here, but i am not sure if the author used these two.
[YOLO_small](https://drive.google.com/file/d/0B2JbaJSrWLpza08yS2FSUnV2dlE/view?usp=sharing)
[YOLO_tiny](https://drive.google.com/file/d/0B2JbaJSrWLpza0FtQlc3ejhMTTA/view?usp=sharing)

**Comment by jiangkun1994** [comment]
For the error

> UnboundLocalError: local variable 'gray' referenced before assignment

There is a file which was not put in the folder so that the `calibration.py' cannot execute correctly, which is

> images = glob.glob('camera_cal/calibration*.jpg')

and you have to fine the source of images for calibration in [self-driving-car](https://github.com/ndrplz/self-driving-car/tree/master/project_4_advanced_lane_finding)
Then, put the file **camera_cal** in the folder with `main.py`
